# .air.toml
# Config file for air: https://github.com/air-verse/air

# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Command to build the app
cmd = "go build -o ./tmp/ignite_karaoke ."
# The binary to run
bin = "./tmp/ignite_karaoke"

# Extensions to watch
include_ext = ["go", "html", "css", "js"]
# Directories to exclude from watching
exclude_dir = ["tmp", "vendor"]

[log]
# Show timestamp in logs
time = true

[misc]
# Clean up tmp dir on exit
clean_on_exit = true 